In [1]:
print 'q chucha'
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

import numpy as np
#import jplus



q chucha


/home/CEFCA/aaorsi/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [1]:
#load databases

import pickle
dset = pickle.load(open('dataset.data'))
print dset.keys()

print 

x_train = np.asarray(dset['tfeatures'])
y_train = np.asarray(dset['tclass'])
x_test = np.asarray(dset['vfeatures'])
y_test    = np.asarray(dset['vclass'])


nfeat = len(x_train[0])
print nfeat
print np.unique(y_train)
#blippi

['tfeatures', 'vclass', 'tclass', 'vfeatures']



NameError: name 'np' is not defined

In [9]:
#Example sets

kx_train = np.random.random((1000, 20))
ky_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
kx_test = np.random.random((100, 20))
ky_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)

print np.shape(kx_train), np.shape(x_train)
print np.shape(ky_train), np.shape(y_train)

def class_to_int(istr):
    if istr == 'OII':
        return 0
    elif istr == 'OIII+Hbeta':
        return 1
    elif istr == 'contaminant':
        return 2
    else:
        print '%s not recognised'%istr
        return -99


y_train_int = [class_to_int(x) for x in y_train]
y_test_int = [class_to_int(x) for x in y_test]

y2_train = keras.utils.to_categorical(y_train_int, num_classes=len(np.unique(y_train_int)))
y2_test = keras.utils.to_categorical(y_test_int, num_classes=len(np.unique(y_test_int)))

print np.shape(y2_train)

print type(y2_train), type(ky_train)

print y2_train[0:2] 
print
print ky_train[0:2]


(1000, 20) (8675, 19)
(1000, 10) (8675,)
(8675, 3)
<type 'numpy.ndarray'> <type 'numpy.ndarray'>
[[0. 1. 0.]
 [0. 1. 0.]]

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
# Keras MLP

model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(3, activation='relu', input_dim=nfeat))
model.add(Dropout(0.5))
model.add(Dense(3, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(3, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])
print 'doing stuff'

print np.shape(x_train)
print np.shape(y2_train)

model.fit(x_train, y2_train,
          epochs=10,
          batch_size=200)

score = model.evaluate(x_test, y2_test, batch_size=100)





doing stuff
(8675, 19)
(8675, 3)
Epoch 1/10
8675/8675 [==============================] - 0s 39us/step - loss: 1.1542 - acc: 0.3343
Epoch 2/10
8675/8675 [==============================] - 0s 10us/step - loss: 1.1118 - acc: 0.3361
Epoch 3/10
8675/8675 [==============================] - 0s 8us/step - loss: 1.1170 - acc: 0.3367
Epoch 4/10
8675/8675 [==============================] - 0s 8us/step - loss: 1.1081 - acc: 0.3333
Epoch 5/10
8675/8675 [==============================] - 0s 8us/step - loss: 1.1168 - acc: 0.3308
Epoch 6/10
8675/8675 [==============================] - 0s 7us/step - loss: 1.1018 - acc: 0.3318
Epoch 7/10
8675/8675 [==============================] - 0s 7us/step - loss: 1.1029 - acc: 0.3360
Epoch 8/10
8675/8675 [==============================] - 0s 6us/step - loss: 1.0993 - acc: 0.3333
Epoch 9/10
8675/8675 [==============================] - 0s 6us/step - loss: 1.1017 - acc: 0.3327
Epoch 10/10
8675/8675 [==============================] - 0s 16us/step


In [16]:
print score

[1.0983815650087956, 0.33475504313147375]
