In [1]:
print 'q chucha'
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

import numpy as np
#import jplus



q chucha


Using TensorFlow backend.
/Users/aaorsi/anaconda/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,


In [3]:
#load databases

DataDir = './data/'

import pickle
dset = pickle.load(open('%s/dataset.data'%DataDir))
print dset.keys()

print 

x_train = np.asarray(dset['tfeatures'])
y_train = np.asarray(dset['tclass'])
x_test = np.asarray(dset['vfeatures'])
y_test    = np.asarray(dset['vclass'])


nfeat = len(x_train[0])
print nfeat
print np.unique(y_train)
#blippi

['tfeatures', 'vclass', 'tclass', 'vfeatures']

19
['OII' 'OIII+Hbeta' 'contaminant']


In [4]:
#Example sets

kx_train = np.random.random((1000, 20))
ky_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
kx_test = np.random.random((100, 20))
ky_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)

print np.shape(kx_train), np.shape(x_train)
print np.shape(ky_train), np.shape(y_train)

def class_to_int(istr):
    if istr == 'OII':
        return 0
    elif istr == 'OIII+Hbeta':
        return 1
    elif istr == 'contaminant':
        return 2
    else:
        print '%s not recognised'%istr
        return -99


y_train_int = [class_to_int(x) for x in y_train]
y_test_int = [class_to_int(x) for x in y_test]

y2_train = keras.utils.to_categorical(y_train_int, num_classes=len(np.unique(y_train_int)))
y2_test = keras.utils.to_categorical(y_test_int, num_classes=len(np.unique(y_test_int)))

print np.shape(y2_train)

print type(y2_train), type(ky_train)

print y2_train[0:2] 
print
print ky_train[0:2]


(1000, 20) (8675, 19)
(1000, 10) (8675,)
(8675, 3)
<type 'numpy.ndarray'> <type 'numpy.ndarray'>
[[0. 1. 0.]
 [0. 1. 0.]]

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


Scale data using scikit-learn StandardScaler

In [6]:
from sklearn.preprocessing import StandardScaler 
Scaledata = True

if Scaledata:
    print 'scaling data...',
    scaler = StandardScaler()
    scaler.fit(x_train)
    x_train = scaler.transform(x_train)
    x_test  = scaler.transform(x_test)
    print 'done'


scaling data... done


In [21]:
# Keras MLP

from keras import metrics

model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(19, activation='relu', input_dim=nfeat))
#model.add(Dropout(0.5))
model.add(Dense(19, activation='relu'))
#model.add(Dropout(0.5))
model.add(Dense(3, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=[metrics.categorical_accuracy])
print 'doing stuff'

print np.shape(x_train)
print np.shape(y2_train)

model.summary()



doing stuff
(8675, 19)
(8675, 3)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_40 (Dense)             (None, 19)                380       
_________________________________________________________________
dense_41 (Dense)             (None, 19)                380       
_________________________________________________________________
dense_42 (Dense)             (None, 3)                 60        
Total params: 820
Trainable params: 820
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.fit(x_train, y2_train,
          epochs=20,
          batch_size=500,
          validation_data=(x_test,y2_test),
          shuffle=True,
          verbose=2
          )

#score = model.evaluate(x_test, y2_test, batch_size=200)

print score

Train on 8675 samples, validate on 8675 samples
Epoch 1/20
 - 3s - loss: 1.1353 - categorical_accuracy: 0.3277 - val_loss: 1.0687 - val_categorical_accuracy: 0.4160
Epoch 2/20
 - 0s - loss: 1.0427 - categorical_accuracy: 0.4808 - val_loss: 1.0124 - val_categorical_accuracy: 0.5229
Epoch 3/20
 - 0s - loss: 0.9916 - categorical_accuracy: 0.5372 - val_loss: 0.9679 - val_categorical_accuracy: 0.5505
Epoch 4/20
 - 0s - loss: 0.9507 - categorical_accuracy: 0.5572 - val_loss: 0.9290 - val_categorical_accuracy: 0.5669
Epoch 5/20
 - 0s - loss: 0.9136 - categorical_accuracy: 0.5720 - val_loss: 0.8938 - val_categorical_accuracy: 0.5801
Epoch 6/20
 - 0s - loss: 0.8801 - categorical_accuracy: 0.5880 - val_loss: 0.8624 - val_categorical_accuracy: 0.5961
Epoch 7/20
 - 0s - loss: 0.8500 - categorical_accuracy: 0.6012 - val_loss: 0.8349 - val_categorical_accuracy: 0.6081
Epoch 8/20
 - 0s - loss: 0.8236 - categorical_accuracy: 0.6142 - val_loss: 0.8088 - val_categorical_accuracy: 0.6247
Epoch 9/20
 - 0s