In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

import numpy as np
#import jplus



Using TensorFlow backend.
/Users/aaorsi/anaconda/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,


In [6]:
#load databases

#DataDir = './data/'
DataDir = '.'
import pickle
dset = pickle.load(open('%s/training_full.data'%DataDir))
print dset.keys()


featnames = ['dm_j0660','J0660','uSDSS','gSDSS','rSDSS','iSDSS','zSDSS']

ntrain = len(dset['obj'])
feat_arr = []

import itertools

terms = featnames[1:] # create all colour combinations
nterms = len(terms)
ncomb = int(nterms*(nterms-1)/2.)
print 'All colours:', ncomb
comb = list(itertools.combinations(terms,2))
lcomb = list(comb)
colournames = ['%s - %s'%(x[0], x[1]) for x in list(comb)]

for x in range(ntrain):
    fx = []
    for y in featnames:
        fx.append(dset[y][x,0])
    for z in range(ncomb):
        fx.append(dset[lcomb[z][0]][x,0] - dset[lcomb[z][1]][x,0])
        
#    fx.append(dset['uSDSS'][x,0]-dset['gSDSS'][x,0])
#    fx.append(dset['gSDSS'][x,0]-dset['rSDSS'][x,0])
#    fx.append(dset['rSDSS'][x,0]-dset['iSDSS'][x,0])
#    fx.append(dset['uSDSS'][x,0]-dset['gSDSS'][x,0])
#    fx.append(dset['iSDSS'][x,0]-dset['zSDSS'][x,0])
#    fx.append(dset['uSDSS'][x,0]-dset['zSDSS'][x,0])
#    fx.append(dset['rSDSS'][x,0]-dset['zSDSS'][x,0])
    
    feat_arr.append(fx)
class_arr = dset['class']
featnames += colournames


['rSDSS', 'iSDSS', 'obj', 'gSDSS', 'zSDSS', 'uSDSS', 'dm_j0660', 'J0660', 'class']
All colours: 15


In [8]:
print featnames, len(featnames)



['dm_j0660', 'J0660', 'uSDSS', 'gSDSS', 'rSDSS', 'iSDSS', 'zSDSS', 'J0660 - uSDSS', 'J0660 - gSDSS', 'J0660 - rSDSS', 'J0660 - iSDSS', 'J0660 - zSDSS', 'uSDSS - gSDSS', 'uSDSS - rSDSS', 'uSDSS - iSDSS', 'uSDSS - zSDSS', 'gSDSS - rSDSS', 'gSDSS - iSDSS', 'gSDSS - zSDSS', 'rSDSS - iSDSS', 'rSDSS - zSDSS', 'iSDSS - zSDSS'] 22


In [17]:
#Example sets

def class_to_int(istr):
    if istr == 'Halpha':
        return 0
    elif istr == 'OIII+Hbeta':
        return 1
    if istr == 'OII':
        return 2
    elif istr == 'contaminant':
        return 3
    else:
        print '%s not recognised'%istr
        return -99


y_train_int = [class_to_int(x) for x in class_arr]
y_train = keras.utils.to_categorical(y_train_int, num_classes=len(np.unique(y_train_int)))
x_train = feat_arr
nfeat = len(feat_arr[0])
print nfeat
print y_train_int



22
[2, 1, 2, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1, 0, 1, 1, 2, 0, 1, 0, 1, 2, 0, 0, 2, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 

Scale data using scikit-learn StandardScaler

In [35]:
from sklearn.preprocessing import StandardScaler 
Scaledata = True

if Scaledata:
    print 'scaling data...',
    scaler = StandardScaler()
    scaler.fit(x_train)
    x_train = scaler.transform(x_train)
    #x_test  = scaler.transform(x_test)
    print 'done'


scaling data... done


In [88]:
# Balance the training set by sub-sampling the contaminant class

all_classes = [0,1,2,3]
nclass = []
selclass = []
yarr = np.asarray(y_train_int)
for ic in all_classes:
    sel = np.where(np.asarray(yarr) == ic)[0]
    nclass.append(len(yarr[sel]))
    selclass.append(sel)


idd = list(np.random.choice(selclass[3], nclass[2]))
print idd, yarr[idd]
nff = sum(nclass)

new_idd = []
for ic in [0,1,2]:
    sel = np.where(yarr == ic)[0]
    new_idd += list(sel)

new_idd += idd
        
y_new = np.asarray([y_train[x] for x in new_idd])
x_new = np.asarray([x_train[x] for x in new_idd])



[213, 775, 898, 499, 786, 1205, 167, 1006, 174, 331, 68, 561, 220, 806, 442, 195, 1127, 1211, 216, 415, 595, 1092, 496, 1097, 392, 1043, 988, 356, 125, 545, 746, 966, 354, 463, 1149, 696, 644, 965, 1087, 937, 696, 1058, 1137, 1036, 995, 457, 260, 740, 442, 84, 701, 829, 750, 266, 1049, 1142, 226, 657, 373, 1078, 453, 393, 558, 1181, 517, 637, 896, 471, 1159, 419, 467, 671, 783, 188, 299, 1096, 750, 213, 541, 634, 474, 434, 1206, 757, 1209] [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3]


In [89]:

print y_new

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1.

In [95]:
# Keras MLP

from keras import metrics

model = Sequential()
model.add(Dense(22, activation='softmax', input_dim=nfeat))
model.add(Dense(22, activation='softmax'))
model.add(Dense(4, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer='adam')

model.summary()



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_34 (Dense)             (None, 22)                506       
_________________________________________________________________
dense_35 (Dense)             (None, 22)                506       
_________________________________________________________________
dense_36 (Dense)             (None, 4)                 92        
Total params: 1,104
Trainable params: 1,104
Non-trainable params: 0
_________________________________________________________________


In [102]:
model.fit(x_new, y_new,
          shuffle=True,
          verbose=1,
          epochs=100
          )



Epoch 1/100
218/218 [==============================] - 0s 168us/step - loss: 1.3120
Epoch 2/100
218/218 [==============================] - 0s 224us/step - loss: 1.3067
Epoch 3/100
218/218 [==============================] - 0s 260us/step - loss: 1.3018
Epoch 4/100
218/218 [==============================] - 0s 289us/step - loss: 1.2966
Epoch 5/100
218/218 [==============================] - 0s 234us/step - loss: 1.2919
Epoch 6/100
218/218 [==============================] - 0s 281us/step - loss: 1.2874
Epoch 7/100
218/218 [==============================] - 0s 221us/step - loss: 1.2827
Epoch 8/100
218/218 [==============================] - 0s 254us/step - loss: 1.2785
Epoch 9/100
218/218 [==============================] - 0s 227us/step - loss: 1.2744
Epoch 10/100
218/218 [==============================] - 0s 211us/step - loss: 1.2704
Epoch 11/100
218/218 [==============================] - 0s 252us/step - loss: 1.2664
Epoch 12/100
218/218 [==============================] - 0s 195us/step - lo

218/218 [==============================] - 0s 177us/step - loss: 0.9702
Epoch 98/100
218/218 [==============================] - 0s 212us/step - loss: 0.9660
Epoch 99/100
218/218 [==============================] - 0s 185us/step - loss: 0.9616
Epoch 100/100
218/218 [==============================] - 0s 202us/step - loss: 0.9574


In [103]:
pred = model.predict(x_new,verbose=1)
pred_class = [np.argmax(x) for x in pred]
y_new_num = [np.argmax(x) for x in y_new]



218/218 [==============================] - 0s 70us/step


In [104]:
from sklearn.metrics import f1_score
score = f1_score(y_new_num, pred_class,average=None)
print score
print np.unique(pred_class)

[0.         0.         0.77837838 0.72906404]
[2 3]


In [105]:
print pred_class
print 

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 3, 3, 2, 3, 2, 2, 2, 2, 3, 2, 3, 2, 3, 2, 3, 2, 2, 3, 3, 2, 3, 3, 2, 2, 2, 2, 3, 2, 3, 2, 2, 2, 2, 3, 3, 2, 3, 3, 3, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

